version: '3.8'

name: devfood 

services:
  
  db:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - db:/var/lib/postgresql/data
  
  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile
    env_file: ../.env
    depends_on:
      - db
    volumes:
      - ../backend:/app
    ports:
      - "8008:8008"
  
volumes:
  db:
