version: '3.3'

volumes:
  db:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: ../.env
    depends_on:
      - db
    command:
      cp -r /app/static/. /static/backend/
    volumes:
      - static:/static/frontend
      - media:/app/media
  frontend:
    build: ../frontend
    command:
      cp -r /app/build/. /static/frontend/
    volumes:
      - static:/static/
  nginx:
    image: nginx:1.22.1
    depends_on:
      - backend
      - frontend
    ports:
      - 8080:80
    volumes:
      - static:/static/
      - media:/media/
      - static:/etc/nginx/conf.d/
      - static:/usr/share/nginx/html/
