version: '3.8'

name: devfood 

volumes:
  db_vol:
  static_vol:
  media_vol:

services:
  
  postgres:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - db:/var/lib/postgresql/data

  backend:
    build:
      context: ../backend
      dockerfile: ../backend/Dockerfile.prod
    env_file: ../.env
    depends_on:
      - postgres
    command: cp -r /app/
    volumes:
      - ../backend:/app
      - static_vol:/app/static
      - media_vol:/app/media
    expose:
      - 8008
    ports:
      - "8008:8008"

  frontend:
    build: ../frontend
    volumes:
      - static_vol:/app/build

  nginx:
    image: nginx:1.22.1
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../docs:/usr/share/nginx/html/api/docs
      - static_vol:/usr/share/nginx/html
      - media_vol:/usr/share/nginx/html/media
