version: '3.8'

name: foodgram

volumes:
  db_vol:
  static_vol:
  media_vol:

services:

  postgres:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - db_vol:/var/lib/postgresql/data

  backend:
    image: antaresweb/foodgram-backend
    env_file: ../.env
    depends_on:
      - postgres
    volumes:
      - media_vol:/app/media
      - static_vol:/app/static

  frontend:
    image: antaresweb/foodgram-frontend
    command: cp -r /app/build/. /static/
    volumes:
      - static_vol:/static
  
  nginx:
    image: nginx:1.22.1
    depends_on:
      - backend
    ports:
      - 8008:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_vol:/usr/share/nginx/html
      - media_vol:/usr/share/nginx/html/media