version: '3.3'
services:

  frontend:
    image: antaresweb/foodgram-frontend
#    build:
#      context: ../frontend
#      dockerfile: Dockerfile
    volumes:
      - ../frontend/:/app/result_build/
  backend:
    image: foodgram-backend
    build:
      context: ../backend
      dockerfile: Dockerfile
  nginx:
    image: nginx:1.22.1
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ../frontend/build:/usr/share/nginx/html/
      - ../docs/:/usr/share/nginx/html/api/docs/
