version: '3.8'

name: foodgram

volumes:
  db_vol:
  static_vol:
  media_vol:

services:
  postges:
    image: postgres:13.10
    env_file: ../.env
    volumes:
      - db_vol:/var/lib/postgresql/data
  backend:
    image: antaresweb/foodgram_backend
    env_file: ../.env
    depends_on:
      - postges
    volumes:
      - media_vol:/app/media
      - static_vol:/app/static
  