version: '3.8'

name: foodgram

volumes:
  db_vol:
  static_vol:
  media_vol:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - db_vol:/var/lib/postgresql/data
  backend:
    image: antaresweb/foodgram_backend
    env_file: .env
    depends_on:
      - db
    volumes:
      - media_vol:/app/media
      - static_vol:/app/static
  frontend:
    image: antaresweb/foodgram_frontend
    command:
      cp -r /app/build/. /static/frontend/.
    volumes:
      - static_vol:static/
  nginx:
    build: ../infra
    depends_on:
      - backend
      - frontend
    command: cp /etc/nginx/nginx.conf /static/nginx/nginx.conf
    ports:
      - 8080:80
    volumes:
      - static:/static/
      - media:/media/
