version: '3.8'

name: food 

volumes:
  db:
  static:
  media:

services:
  db:
    image: postgres:13.10
    env_file: ../.env
    ports:
      - 5432:5432
    volumes:
      - db:/var/lib/postgresql/data
  backend:
    build: ../backend/
    env_file: ../.env
    depends_on:
      - db
    command:
      cp -r /app/static/. /static/backend/.
    volumes:
      - static:/static/
      - media:/app/media
  frontend:
    build: ../frontend
    command:
      cp -r /app/build/. /static/frontend/.
    volumes:
      - static:/static/
  nginx:
    build: ../infra
    depends_on:
      - backend
      - frontend
    command: cp /etc/nginx/nginx.conf /static/nginx/nginx.conf
    ports:
      - 8080:80
    volumes:
      - static:/static/
      - media:/media/
