# Generated by Django 3.2.16 on 2023-08-30 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_auto_20230829_1943'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='content',
            options={'ordering': ('recipe', 'ingredient'), 'verbose_name': 'Состав', 'verbose_name_plural': 'Состав'},
        ),
    ]
