# Generated by Django 3.2.16 on 2023-07-06 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('essences', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(through='essences.Content', to='essences.Ingredient'),
        ),
        migrations.AlterField(
            model_name='content',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essences.ingredient'),
        ),
        migrations.AlterField(
            model_name='content',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essences.recipe'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='recipe',
            field=models.ManyToManyField(blank=True, related_name='shoppingcarts', to='essences.Recipe', verbose_name='Список рецептов для закупки ингредиентов'),
        ),
        migrations.AlterField(
            model_name='shoppingcart',
            name='siteuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shoppingcarts', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
