# Generated by Django 3.2.16 on 2023-07-05 10:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essences', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Ingredients',
            new_name='ingredients',
        ),
    ]
