# Generated by Django 3.2.16 on 2023-07-07 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('essences', '0003_auto_20230706_0733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='ingredient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='essences.ingredient'),
        ),
        migrations.AlterField(
            model_name='content',
            name='recipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='essences.recipe'),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='ingredients',
            field=models.ManyToManyField(related_name='recipes', through='essences.Content', to='essences.Ingredient'),
        ),
    ]
