# Generated by Django 3.2.16 on 2023-07-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('essences', '0005_rename_tag_recipe_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='igredient',
            new_name='ingredient',
        ),
    ]
